name: build-and-push
on:
  push:
    branches: [ main ]
env:
  AWS_REGION: ap-south-1
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: proxy
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          SHA: ${{ github.sha }}
        run: |
          docker build -t $REGISTRY/week6-proxy:$SHA -t $REGISTRY/week6-proxy:latest ./proxy
          docker push $REGISTRY/week6-proxy:$SHA
          docker push $REGISTRY/week6-proxy:latest
      - name: backend
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          SHA: ${{ github.sha }}
        run: |
          docker build -t $REGISTRY/week6-backend:$SHA -t $REGISTRY/week6-backend:latest ./backend
          docker push $REGISTRY/week6-backend:$SHA
          docker push $REGISTRY/week6-backend:latest
